#!/bin/bash
set -e

function setup() {
  echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list
  apt-get update -y
  apt-get upgrade -y
  apt-get install -y python-pip screen vim
  apt-get install -t jessie-backports -y openjdk-8-jre-headless ca-certificates-java
  pip install --upgrade awscli
}

function load_server() {
  cd '/home/admin'
  su - 'admin' -c "aws s3 cp s3://${s3_bucket}/backups/minecraft.tar.gz . --region ${region}"
  su - 'admin' -c "tar -xzf minecraft.tar.gz"
  su - 'admin' -c "/home/admin/minecraft/server start"
}

function create_crontab() {
  # Create a backup every other hour
  echo "0 */2 * * * /home/admin/minecraft/server backup &>/home/admin/minecraft/logs/backup.log" >> cronjobs
  # Stop minecraft and create a backup (this should happen before the ASG shutdown)
  echo "30 3 * * * /home/admin/minecraft/server shutdown &>/home/admin/minecraft/logs/shutdown.log" >> cronjobs
  crontab -u 'admin' cronjobs
  rm cronjobs
}

# Main
setup
load_server
create_crontab
